[pytest]
minversion = 6.0
addopts = -ra -q -p no:cacheprovider
log_cli = true
testpaths = tests
python_files = test_*.py
markers =
    sequential: Run this test sequentially
    parallel: Run this test in parallel
    Cucumber: Cucumber scenario
